spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc9th_workbook
    username: root
    password: nyny1102!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
